### ISSUE TITLE
Clarify "bitshift and bit operators"

### ISSUE THREAD

**Issue by beaugunderson** [AugurProject/augur-bounties#1]
Does this include all of these?

- Bitwise NOT `~`
- Bitwise shift operators `<<`,  `>>`
- Bitwise AND `&`
- Bitwise XOR `^`
- Bitwise OR `|`
- Bitwise assignment operators `|=`, `^=`, `&=`, `<<=`, `>>=`

**Comment by tinybike** [comment]
Yep!

**Comment by beaugunderson** [comment]
👍
