### ISSUE TITLE
Bounty Payment

### ISSUE THREAD

**Issue by bwitt2** [AugurProject/augur-bounties#13]
Hi, 

I am requesting bounty payment for my contribution to Solium. I completed the following rule:  Prohibit use of selfdestruct/suicide. My ETH address is:

0x0025a326D85Db50074DcabC9dC33cbF63F1A7709

Thanks :)

**Comment by beaugunderson** [comment]
@bwitt2 i pinged the augur folks for you, they should send payment soon! 👍

**Comment by ghost** [comment]
Apologies for the delay, payment sent! Thanks for your contribution!

https://etherscan.io/tx/0x04b53ee610c29836f9173dfef8ad87d974e1606064217d740def24b651f0afef
