### ISSUE TITLE
Clarify "function overriding"

### ISSUE THREAD

**Issue by beaugunderson** [AugurProject/augur-bounties#2]
Does this refer to contract overrides, e.g. the `contract A is B, X` syntax?

**Comment by tinybike** [comment]
It refers to overrides of inherited functions.  For example, where you have `contract A is B` and `B` has a function `funFunction`, and `A` defines its own `funFunction` with the same name and signature as `B`'s `funFunction`, which overrides `B`'s `funFunction`.
