### ISSUE TITLE
Clarify "Only one break statement allowed per loop"

### ISSUE THREAD

**Issue by duaraghav8** [AugurProject/augur-bounties#4]
As I understand, this rule gets violated if > 1 `break` statements exist in any loop.
In below example:

```
for(uint i = 0; i < 10; i++) {
            break;

            for (uint j = 0; j < 10; j++) {
                break;
            }
}
```

Should the outer `for` loop get flagged by this rule? (Same with any combination of nested loops)

**Comment by tinybike** [comment]
The intention with this rule is that a loop should just have a single exceptional exit.  So, in your example, the inner loop would be allowed its own break, and the outer loop would not be flagged.

Sorry for the ambiguity.  Maybe the rule should be reworded to say that there's _only one break statement allowed per loop that pertains to exit from that loop_... :thinking:
