### ISSUE TITLE
clarify "Functions must have an explicit return statement"

### ISSUE THREAD

**Issue by duaraghav8** [AugurProject/augur-bounties#5]
I'm not sure of the significance of "explicit" and the meaning of the rule in general.

Do you mean the rule should enforce a top-level return statement inside the function declaration?

1
```
function foo() {
    blah(123);
    return 100;
}
```

2
```
function foo() {
    blah(123);
}
```

3
```
function foo() {
    if (...) { return 1; }
    else { return 2; }
}
```

4
```
function foo() {
    do {
        return "hello world";
    } while (true);
}
```

Which of the above SHOULD be flagged as violation by this rule? (2 will obvio be flagged)

cc: @tinybike @beaugunderson @nfeignon

https://github.com/duaraghav8/solium-plugin-security/pull/10

**Comment by tinybike** [comment]
Sorry for the unclear wording!  A better description for this rule might be "no named returns".  Solidity lets you do this:
```
function funnestFunction() returns (uint256 funnestReturnValue) {
    funnestReturnValue = 42;
}
```
This function returns `42` without an explicit return statement, which is confusing.  Much better to do it the "normal" way, declaring a return type in the function signature and using an explicit return statement in the function body:
```
function funnestFunction() returns (uint256) {
    return 42;
}
```
Does this make sense?

**Comment by tinybike** [comment]
Addendum: while typing this, I realized that there should also be a rule which requires all functions to declare a return type (i.e., no void returns).  The idea is that people have a tendency to assume that functions return `true` on success, and if functions don't return anything that can be a source of bugs.

I think this is conceptually separate from the rule in this issue, though, so I'll add a new item to the linter bounties list today for this semi-related "no-void-returns" rule :smile:

**Comment by duaraghav8** [comment]
Ah! That makes sense
