### ISSUE TITLE
Clarify 'testrpc' (Bounty 2)

### ISSUE THREAD

**Issue by cgewecke** [AugurProject/augur-bounties#6]
There are currently two projects using this name:
+ `ethereumjs-testrpc` (running ethereumjs-vm / provides a `debug_traceTransaction` endpoint similar to [Geth's](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_tracetransaction))
+ `eth-testrpc` (running pyethereum).

Which are you targeting? Both? 

If pyethereum one way to simplify this bounty might be to break the `debug_traceTransaction` piece out and encourage that [endpoint's development](https://github.com/pipermerriam/eth-testrpc/issues/88) at `eth-testrpc` separately. The trace is necessary to implement a debugger.

(Off-topic but highest props to you Augur for running this kind of bounty program. You are a model).

**Comment by duaraghav8** [comment]
@tinybike ^

**Comment by cgewecke** [comment]
On reflection it might be even better if both of these clients provided a straightforward way to subscribe to the VM `step` (maybe via web-sockets as part of their efforts to integrate Web3 1.0). This would make it possible for a debugger to investigate the execution of calls as well as sends.  

ethereumjs-vm exposes an [event hook](https://github.com/ethereumjs/ethereumjs-vm#step) for this - not positive but I don't think pyethereum does.

**Comment by tinybike** [comment]
We're specifically targeting ethereumjs-testrpc.  (pyethereum is nice but my understanding is that it is being officially sunsetted, so we don't want to throw more resources than is necessary into it.)

**Comment by cgewecke** [comment]
@tinybike Thanks, closing.
