### ISSUE TITLE
Clarify intended workflow (Bounty 2)

### ISSUE THREAD

**Issue by cgewecke** [AugurProject/augur-bounties#7]
The workflow you've described seems patterned on traditional debuggers like gdb. Are you hoping for a solution that allows you start/stop the VM as it executes the tests? 

An alternate workflow, one that Truffle is pursuing, might be:
+ Run all the tests, recording the vm state as they execute.
+ Once tests crash, drop into debugger.
+ Set breakpoint
+ "Run" across the record to the breakpoint, etc.

If the latter is acceptable, this debugger starts to look like 3 programs - a JS plugin to a JS testing framework that compiles an execution trace, a Python plugin for a Python testing framework which does the same, and finally a simulator that executes the trace in a searchable, human-readable format. 

[EDIT] 
If it's possible to subscribe to the vm step somehow, it might look more like this:
```
$ sdb --command "npm test" --port 8545
> (sdb) setBreakpoint Token.sol:105
> (sdb) run
``` 
where sdb opens a socket to the rpc and records everything as it happens from outside without having to worry about the tests calling `evm_revert` / erasing parts of the execution record between test start and finish.

**Comment by ghost** [comment]
cc: @tinybike

**Comment by cgewecke** [comment]
Closing. If there's something to clarify here please feel free to re-open.
